blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/yourusername/markdown-server/discussions
    about: Ask questions or discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/yourusername/markdown-server/security
    about: Report security vulnerabilities privately (see SECURITY.md)
